export const GAME_CONSTANTS = {
  CLICK_DEBOUNCE_MS: 60,
  CLICK_PRECISION_THRESHOLD: 5,
  SUSPICIOUS_CLICK_THRESHOLD: 5,
  CLICK_MESSAGE_LIFETIME_MS: 500,
  CLICK_MESSAGE_REMOVE_DELAY_MS: 800,
  SCALE_ANIMATION_DURATION_MS: 100,
};
